// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7x9eG9xOFPpLMCvxSEmrkF7jAK9osQU',
    appId: '1:1002306876322:android:269bf6b91b8e22e37678fb',
    messagingSenderId: '1002306876322',
    projectId: 'mis-domasna',
    storageBucket: 'mis-domasna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvHnZduE_jAuC1Ci-XnjnkZiy3LNS3dA',
    appId: '1:1002306876322:ios:b4f593966015aa117678fb',
    messagingSenderId: '1002306876322',
    projectId: 'mis-domasna',
    storageBucket: 'mis-domasna.firebasestorage.app',
    iosBundleId: 'com.example.domasna2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBlMOHkAVzdE-vxWsQWCCFVBZyMwP9oUQ',
    appId: '1:1002306876322:web:24a43a5c639645087678fb',
    messagingSenderId: '1002306876322',
    projectId: 'mis-domasna',
    authDomain: 'mis-domasna.firebaseapp.com',
    storageBucket: 'mis-domasna.firebasestorage.app',
    measurementId: 'G-V0SN136Y7Z',
  );
}
